### PR TITLE
Add Nord associated websites 

### PR DESCRIPTION
**Pull request by ChrisMarstaller**
### Overall Checklist
- [x] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [x] The top-level JSON objects are sorted alphabetically
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

#### for websites-with-shared-credential-backends.json
- [x] There's evidence the domains are related (SSL certificates, DNS entries, valid links between sites, legal documents etc.)
- [x] The new group serves login pages on each of the included domains, and those login page accept accounts from the others. (For example, we don't associate `google.co.il` to `google.com`, because `google.co.il` redirects to `accounts.google.com` for authentication.)

### CODE REVIEW

**Comment by rmondello** [comment]
All of the domains (sans nordaccount) redirect to nordaccount, so I don’t think it’s appropriate to incorporate this change as-is. @Cldfire

**Comment by Cldfire** [comment]
> All of the domains (sans nordaccount) redirect to nordaccount, so I don’t think it’s appropriate to incorporate this change as-is. @Cldfire

Correct; this would be best suited as part of the format detailed in #389.

That being said, I'm unable to find a login form being served under a URL other than `https://my.nordaccount.com/login`, which means no entry should be required for these sites. @ChrisMarstaller, have you encountered a login for one of these accounts that is _not_ served under the `nordaccount.com` domain? If so, would you be able to share some steps to find the login form? 😄

**Comment by ChrisMarstaller** [comment]
Apparently, my account was still on their old authentication method when I submitted the pull request, but I've since been upgraded to Nord Account and I'm seeing the same result as @rmondello. 

However, I noticed they are using both nordaccount.com and ndaccount.com (I did a password reset and it uses this domain) for authentication. The branch was updated with the domain changes.

**Comment by ChrisMarstaller** [comment]
Since the domains are no longer being actively used, I'm closing this pull request and will revisit when a new format is available to handle historic data.

**Pull request closed without merging**
