### PR TITLE
Add password rules for ventrachicago.com

### PR DESCRIPTION
**Pull request by davidjohnson91**
### Overall Checklist
- [x] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [x] The top-level JSON objects are sorted alphabetically
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

#### for change-password-URLs.json
- [x] There is no Well-Known URL for Changing Passwords (`https://example.com/.well-known/change-password`)
- [x] The URL either makes the experience better or no worse than being directed to just the domain in a non-logged-in state

#### for password-rules.json
- [x] The given rule isn't particularly standard and obvious for password managers
- [x] Generated passwords have been tested from this rule using the [Password Rules Validation Tool](https://developer.apple.com/password-rules/)
- [x] Information has been included about the website's requirements (eg. screenshots, error messages, steps during experimentation, etc.)
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)

When changing a password, the rules are outlined as:
> Password must have a minimum of 8 characters and include one upper case letter, one lower case letter, and at least one number or one of these characters (!@#$%^) No other characters are allowed.

### CODE REVIEW

**Comment by jumoru** [comment]
Looks fine to me. The only little thing I've noticed is that, given they require a number **or** (!@#$%^), the password rule could be made a bit less restrictive (`required: digit, [!@#$%^];` instead of  `required: digit; required: [!@#$%^];`).

**Comment by rmondello** [comment]
@davidjohnson91 What do you think about making this?

```
required: lower; required: upper; required: digit, [!@#$%^];
```

As @jumoru suggests.

**Comment by davidjohnson91** [comment]
Thanks for the feedback everyone, I'm still learning the syntax for these rules a bit. I also verified that the description is correct and that `digit || [!@#$%^]` causes a password to be accepted.

**Comment by rmondello** [comment]
@davidjohnson91 Learning is good. :)

Thanks for the PR!

**Pull request merged**
