### PR TITLE
Add banner aetna and aetna.com to shared credentials

### PR DESCRIPTION
**Pull request by kylesethgray**
whois aetna.com: 
> Registrant Email: domains@aetna.com
Registry Admin ID: 
Admin Name: Domain Administrator
Admin Organization: Aetna Life Insurance Company
Admin Street: 151 Farmington Ave, 

whois myplanportal.com:

>Registrant Email: domains@aetna.com
Registry Admin ID: 
Admin Name: Domain Administrator
Admin Organization: Aetna Life Insurance Company
Admin Street: 151 Farmington Ave, 

-- 
Same website credentials on either. 😁

### CODE REVIEW

**Comment by kylesethgray** [comment]
This may not seem to make sense when you navigate to myplanportal.com and it automatically redirects.


However, Aetna partnerships create URLs like "https://member.banneraetna.myplanportal.com/appConfig/login/login.fcc" on top of Aetna's authentication, thus needing the shared credentials for aetna.com and myplanportal.com since they both work.

**Comment by DerJuulsn** [comment]
@kylesethgray I think you should add **banneraetna.myplanportal.com** instead of just **myplanportal.com**, would make more sense to me.

**Comment by DerJuulsn** [comment]
And would you mind to change the title to sth more meaningful? :)

**Comment by rmondello** [comment]
I agree with @DerJuulsn’s suggestions.

**Comment by kylesethgray** [comment]
Thanks all! 😄

**Pull request merged**
