### PR TITLE
Add marktplaats.nl change password url

### PR DESCRIPTION
**Pull request by daannijkamp**
Ebay is called Marktplaats.nl in the Netherlands

https://www.marktplaats.nl/.well-known/change-password is not implemented

### CODE REVIEW

**Comment by rmondello** [comment]
Hey @daannijkamp! Is this a password change page, or a password reset page?

**Comment by DerJuulsn** [comment]
It's a change password site.
@daannijkamp can you resolve the merge conflicts?

**Comment by rmondello** [comment]
Thanks @DerJuulsn! (And thanks for everything, in general!)

I fixed the merge conflict.

**Comment by rmondello** [comment]
Thanks for submitting this, @daannijkamp!

**Pull request merged**
