### PR TITLE
add kansas city, st louis, and seattle library groups to shared backends

### PR DESCRIPTION
**Pull request by geoffcline**
based on the discussion in #144 -- i added the following library groups. 

They all include subdomains of [libraryname].overdrive.com

It's definitely confusing to keep track of the Seattle Public Library (SPL), St Louis Public Library (SLPL), St Louis County Library (SLCL), Kansas City Library (KCL), and King County Library System (KCLS). 

### Checklist
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)
- [ ] The top-level JSON objects are sorted alphabetically 
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update.

#### for websites-with-shared-credential-backends.json
- [x] The new group serves login pages on each of the included domains, and those login page accept accounts from the others. (For example, we don't associate `google.co.il` to `google.com`, because `google.co.il` redirects to `accounts.google.com` for authentication.)

#### for change-password-URLs.json
- [ ] There is no Well-Known URL for Changing Passwords (`https://example.com/.well-known/change-password`)

### CODE REVIEW

**Comment by geoffcline** [comment]
oh, and yes I did triple check that login pages are served for each of these domains B)

**Comment by igor-makarov** [comment]
Wait, so different subdomains of `bibliocommons.com` would have different credential backends? 😭

**Comment by geoffcline** [comment]
yes! it is a pain! i tried to say this in #144 but it appears it is still an issue ... let me know how I can clarify or help.

**Comment by rmondello** [comment]
One thing that we’ve done with iCloud Keychain is put bibliocommons.com on a short list of websites that are known to be affiliated with so many different credential backends that it doesn’t make sense to warn users about password reuse with that website, because the odds of it being a legitimate manifestation of a shared credential backend situation are too high. We thought this list and purpose was pretty specific to our product, but this may not be the case.

**Comment by rmondello** [comment]
Looks like we need some rebasing.

**Comment by geoffcline** [comment]
I’ll do more thinking on the concept of a “sub domains with different backends” list compared to the current “websites with shared backends” list.

Libraries also have the interesting pattern of the credentials (usually) being an assigned barcode as the username and a four digit pin.

I think it’s worthwhile here — the assigned barcode is a pain to remember, and as we can see here you enter it on a variety of different sites.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rmondello** [comment]
@geoffcline I’d love to help you get this merged. Can you fix up the merge conflicts?

**Comment by geoffcline** [comment]
Yes, I will fix the conflicts soon. Thank you!
________________________________

**Comment by rmondello** [comment]
I know that @geoffcline really wants to get this in, so leaving this open. (I’m doing a pass of open PRs right now.)

**Comment by geoffcline** [comment]
no more conflicts ! ! ! 🥳

thanks for waiting.

**Pull request merged**
