### PR TITLE
Add Githubs Change Password URL

### PR DESCRIPTION
**Pull request by dikti**

### CODE REVIEW

**Comment by rmondello** [comment]
Github appears to have adopted the Well-Known URL for Changing Passwords, so I’m not sure if it’s appropriate to incorporate a quirk. There’s no need! @dikti, does that make sense?

**Comment by rmondello** [comment]
For reference: https://github.com/.well-known/change-password

**Comment by dikti** [comment]
You’re right, my bad.

**Comment by bradcush** [comment]
@rmondello Are you aligned with creating a list of sites that support the "Well-Known URL for Changing Passwords"?

**Comment by rmondello** [comment]
Good question, @bradcush. I don’t think that falls within the spirit of the project, which is to gather data to help password managers help users. Listing out website that do support the well-known change password URL doesn’t really do that. Does that make sense? What do you think?

**Comment by bradcush** [comment]
@rmondello Makes sense, thanks!

**Pull request closed without merging**
