### PR TITLE
Add joyn.de

### PR DESCRIPTION
**Pull request by janek26**
### Checklist
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)
- [x] The top-level JSON objects are sorted alphabetically 
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update.

#### for websites-with-shared-credential-backends.json
- [x] The new group serves login pages on each of the included domains, and those login page accept accounts from the others. (For example, we don’t associate google.com.li to google.com, because google.com.li redirects to accounts.google.com for authentication.)

#### for change-password-URLs.json
- [x] There is no Well-Known URL for Changing Passwords (`https://example.com/.well-known/change-password`)

### CODE REVIEW

**Comment by rmondello** [comment]
Can you give me a little bit more context about joyn.at? It looks like it’s not fully up and running right now?

**Comment by janek26** [comment]
true, it‘s not right now. Should I remove it til then?

**Comment by igor-makarov** [comment]
Are you the developer for the websites? Because if you are, there's a better way to support password change, and it's preferred:  
`https://example.com/.well-known/change-password`

This way, you do not need to be on the password change list.

**Comment by janek26** [comment]
Alright, I can adopt that. 
Can we keep the `websites-with-shared-credential-backends.json` modification?

**Comment by igor-makarov** [comment]
Yes, I think there's no decentralized alternative for this. Am I right @rmondello?

**Comment by rmondello** [comment]
@janek26 Are you going to offer login web pages on both websites that use the same credential backend? That’s the only legitimate reason to be added to this list. But really, the best practice is for you to use a more SSO approach, where login is centralized to a single domain.

**Comment by janek26** [comment]
Alright, thanks for the feedback 👍

**Comment by rmondello** [comment]
I super appreciate your enthusiasm for this! And I’m happy that in these cases, we don’t need to add quirks for your website, because you can go and do the right things! :-)

**Pull request closed without merging**
