### PR TITLE
add univ. of missouri domains w/ shared backend

### PR DESCRIPTION
**Pull request by geoffcline**
### Checklist
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)
- [x] The top-level JSON objects are sorted alphabetically 
- [x] There is no Well-Known URL for Changing Passwords (`https://example.com/.well-known/change-password`)
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update.

### CODE REVIEW

**Comment by rmondello** [comment]
And there are login pages on each of these websites that all can be signed into with the same credentials?

**Comment by geoffcline** [comment]
yes, they share a common active directory domain. 

for example, I can login to these sites with the same login
https://login.libproxy.mst.edu/login
https://ill.mul.missouri.edu/
https://www.umkc.edu/is/support/services/purchasing/software/Adobe.asp

**Comment by rmondello** [comment]
And this is true for all five?

It also looks like there’s a conflict. Can you resolve that?

**Comment by geoffcline** [comment]
Yes, it is true for all five. 

here are examples for the remaining 2 domains
https://sharepoint.umsystem.edu/
https://myview.umsl.edu/psp/csprds/?cmd=login&languageCd=ENG&

The same username/password/profile works on all 5 examples.

**Comment by rmondello** [comment]
Sounds good. Looks like the current PR merges them into another group, rather than adding a new group.

**Comment by geoffcline** [comment]
learning git one step at a time B) 

thanks! -- fixed in 5a0e81a (split the group)

**Comment by rmondello** [comment]
I look forward to the University of Michigan one day adopting an SSO solution.

**Comment by rmondello** [comment]
Thanks for putting up with all of the back and forth on this one, @geoffcline!

**Comment by geoffcline** [comment]
no problem! thank you!

and for the record, they are working on a SSO solution (https://shib-idp.umsystem.edu/)

it's been in the works for at least 8 years. new apps use it, but the old things (peoplesoft campus, peoplesoft financial, library services), have huge userbases and are also proving difficult to update.

**Pull request merged**
