### PR TITLE
Add password rules for prepaid.bankofamerica.com

### PR DESCRIPTION
**Pull request by kylesethgray**
Slightly different from BankofAmerica.com [see screenshot] - validated by going to prepaid.bankofamerica.com/[subDirectory]/PasswordChange and testing from password rule generator.

### Checklist
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)
- [x] The top-level JSON objects are sorted alphabetically 
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update.

### CODE REVIEW

**Comment by kylesethgray** [comment]
>Password must contain 8 - 16 characters, including 1 upper case letter,1 lower case letter, 1 number and 1 special character. Password cannot contain your First Name, Last Name, or Username.

**Comment by kylesethgray** [comment]
Screen Shot 2020-06-08 at 1 36 54 PM

**Comment by kylesethgray** [comment]
Should subdomains be sorted alphetically separately from the domain objects? 

i.e. should it be 

bankofamerica.com
prepaid.bankofamerica.com
chase.com


or 

bankofamerica.com
chase.com
prepaid.bankofamerica.com

**Comment by kylesethgray** [comment]
Updated based on existing sorting to put 'prepaid.bankeofamerica.com' near the 'p's in the file, rather than next to 'bankofamerica.com'

**Comment by kylesethgray** [comment]
Screenshot featuring Bank of America site showing 'invalid' based on Safari's automatically generated 'strong password'.
Screen Shot 2020-06-08 at 1 36 58 PM

**Comment by kylesethgray** [comment]
Ok after all that hullabaloo, ready for review!

**Comment by rmondello** [comment]
Thanks @kylesethgray!

**Pull request merged**
