### PR TITLE
Added change password URL for Telekom.de (Telekom.com?)

### PR DESCRIPTION
**Pull request by m33x**
That's a difficult one, the German telekom.de and its news website t-online.de authenticate via telekom.com. I don't have a telekom.com (US) account, thus, I cannot verify whether this link also works for telekom.com, thus, I opted to add it as "telekom.de".

### Checklist
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)
- [x] The top-level JSON objects are sorted alphabetically 
- [x] There is no Well-Known URL for Changing Passwords (`https://example.com/.well-known/change-password`)
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update.

### CODE REVIEW

**Comment by rmondello** [comment]
Oh, this one is a bit trickier. I’ll think about this a bit.

**Comment by DerJuulsn** [comment]
Telekom.com isn't American. It's German.
The American website is t-mobile.com

**Comment by DerJuulsn** [comment]
Bildschirmfoto 2020-06-06 um 23 43 48

**Comment by rmondello** [comment]
If the authentication is done via telekom.com, would a user even have a saved password for telekom.de in the first place?

**Comment by DerJuulsn** [comment]
I've just realized, there isn't even a possibility to log-in on telekom.com just telekom.de
That solves the problem, doesn't it? :)

**Comment by rmondello** [comment]
Seems like. What do you think, @m33x?

**Comment by m33x** [comment]
Yes, correct, so using 'telekom.de' as identifier was the correct choice. I suggest you allow the merge.

**Comment by DerJuulsn** [comment]
Agree.

**Comment by rmondello** [comment]
Thanks @m33x!

**Pull request merged**
