### PR TITLE
cathaypacific.com policy

### PR DESCRIPTION
**Pull request by TheTimewaster**
### Overall Checklist
- [x] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [x] The top-level JSON objects are sorted alphabetically
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

#### for password-rules.json
- [x] The given rule isn't particularly standard and obvious for password managers
- [x] Generated passwords have been tested from this rule using the [Password Rules Validation Tool](https://developer.apple.com/password-rules/)
- [x] Information has been included about the website's requirements (eg. screenshots, error messages, steps during experimentation, etc.)
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)

grafik

### CODE REVIEW

**Comment by rmondello** [comment]
I think the best rule for this website is:

```
"password-rules": "minlength: 8; maxlength: 20; required: upper; required: digit; required: [!#$*^]; allowed: lower;"
```

@TheTimewaster What do you think?

**Comment by TheTimewaster** [comment]
@rmondello You are totally right. It double checked it and looks correct now.

image

**Comment by rmondello** [comment]
Your rule says "require one of upper or digit", but I think you want, "require one upper. require one digit".

`minlength: 8; maxlength: 20; required: upper; required: digit; allowed: lower; required: [!#$*^];`

**Comment by TheTimewaster** [comment]
Alright. Thanks for pointing out. I changed it accordingly.

**Review by rmondello — APPROVED** [review]

**Comment by rmondello** [comment]
Thank you so much, @TheTimewaster!

**Pull request merged**
