### PR TITLE
Added Netflix's change URL and Microsoft related domains

### PR DESCRIPTION
**Pull request by valentinvarbanov**
Added change url and more domains to Microsoft' shared backend group

This is a copy of #23 but with fixed source branch

### CODE REVIEW

**Comment by DerJuulsn** [comment]
@valentinvarbanov can you resolve the merge conflicts? :)

**Comment by valentinvarbanov** [comment]
@DerJuulsn Done, merge conflicts are resolved.

**Comment by DerJuulsn** [comment]
@rmondello could you take a look on this one? :)

**Comment by rmondello** [comment]
Thanks for reviewing this, @DerJuulsn!

**Pull request merged**
