### PR TITLE
Add linkedin.com change password URL

### PR DESCRIPTION
**Pull request by tomjirinec**
Updated with additional providers

### CODE REVIEW

**Comment by rmondello** [comment]
Hey @tomjirinec! Would you mind changing the title of your PR to better reflect what changes you’re making? Something like, “Add upc.cz and linkedin.com change password urls”.

It also looks like the linkedin.com URL is a reset password URL, not a change password page. Can you take another look at that?

**Comment by tomjirinec** [comment]
> Hey @tomjirinec! Would you mind changing the title of your PR to better reflect what changes you’re making? Something like, “Add upc.cz and linkedin.com change password urls”.
> 
> It also looks like the linkedin.com URL is a reset password URL, not a change password page. Can you take another look at that?

Will do, thanks for the suggestions Ricky!

**Comment by DerJuulsn** [comment]
@tomjirinec are you still working on this one? :)

**Comment by rmondello** [comment]
I fixed this up. Merged.

**Comment by rmondello** [comment]
Thanks @tomjirinec!

**Pull request merged**
