### PR TITLE
Added app.digiboxx.com in password-rules

### PR DESCRIPTION
**Pull request by amalgopal2015**
### Overall Checklist
- [x] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [x] The top-level JSON objects are sorted alphabetically
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

#### for password-rules.json
- [x] The given rule isn't particularly standard and obvious for password managers
- [x] Generated passwords have been tested from this rule using the [Password Rules Validation Tool](https://developer.apple.com/password-rules/)
- [x] Information has been included about the website's requirements (eg. screenshots, error messages, steps during experimentation, etc.)
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)

### CODE REVIEW

**Comment by amalgopal2015** [comment]
Added **app.digiboxx.com** in password-rules


Screenshot 2024-02-19 020512

**Comment by rmondello** [comment]
Hi @amalgopal2015! How did you come up with that list of special characters? Did the website list them, or did you try experimentally?

**Comment by kiddailey** [comment]
I took a look at this by verifying each character individually (the site highlights when the requirement has been met) and the commit is not quite correct.  The site requires at least one of the 0-8 number key symbols [!@#$%^&*].  The change submitted is missing the asterisk character.

The 9 and 0 key open and close parenthesis do NOT fulfill the symbol requirement.  Nor do any of the other keyboard symbols ~`-_=+[{]}\|;:'",<.>/?  However, any of these symbols are allowed -- they just don't fulfill the requirement.

**Review by rmondello — APPROVED** [review]

**Comment by dmmaslenn** [comment]
I have updated this PR to include special characters mentioned on the app.digiboxx.com sign up page:
Screenshot 2024-09-27 at 3 30 47 PM

**Pull request merged**
