### PR TITLE
add williams-sonoma inc sites with shared backends

### PR DESCRIPTION
**Pull request by bradcush**
Add Williams-Sonoma Inc. partner sites with shared backends using the same login credentials

### CODE REVIEW

**Comment by geoffcline** [comment]
I double checked these retail sites shared a backend.

**Comment by rmondello** [comment]
I’m working through some of the older PRs. Some comments:

1. This needs to be updated to merge cleanly.
2. And we’re sure that each of these domains serves a login page, rather than redirecting to one login page on one domain?

**Comment by bradcush** [comment]
@rmondello Apologies for the delayed response... I've updated the PR so it can be merged cleanly. When I created it I also verified that each domain I've listed serves it's own login page for it's own domain, and that it's not shared.

**Comment by rmondello** [comment]
Thanks @bradcush!

**Pull request merged**
