### PR TITLE
Improved consistency of entries

### PR DESCRIPTION
**Pull request by CasualDeveloper**
### Changes Made
A. Consolidating multiple "required: " or "allowed: " tags into a single tag, eg. from `"required: lower; required: upper; required: digit; required: [!#$%&*@^];"` into `"required: lower, upper, digit, [!#$%&*@^];"`

B. Rearranging quirks (when present) into the following order:
1. minlength
2. maxlength
3. max-consecutive
4. required
5. allowed

### Overall Checklist
- [X] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [X] The top-level JSON objects are sorted alphabetically
- [X] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

#### for password-rules.json
- [X] The given rule isn't particularly standard and obvious for password managers
- [X] Generated passwords have been tested from this rule using the [Password Rules Validation Tool](https://developer.apple.com/password-rules/)
- [X] Information has been included about the website's requirements (eg. screenshots, error messages, steps during experimentation, etc.)
- [X] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)

### CODE REVIEW

**Comment by Cldfire** [comment]
Hi! Thanks for taking the time to organize things a bit :)

The ordering of the properties in each entry (point B) is a great touch (although I don't believe we have any plans to enforce a specific ordering, so entries added after this won't necessarily be the same.)

The various `required` properties were separate for a reason, though, so you're going to need to revert point A. For instance, in this PR line 6 has been changed from:

```
"password-rules": "minlength: 6; required: lower, upper; required: digit;"
```

to:

```
"password-rules": "minlength: 6; required: lower, upper, digit;"
```

The former (`required: lower, upper; required: digit;`) says "this password needs at least one lowercase or uppercase letter **and** at least one digit." The latter (`required: lower, upper, digit;`) says "this password needs at least one lowercase, uppercase, **or** digit character. These two properties are semantically different, so it's not ok to combine them.

(It's ok to combine multiple `allowed` properties into one, though; `allowed: lower; allowed: upper` and `allowed: lower, upper` *do* semantically represent the same password rule.)

**Comment by CasualDeveloper** [comment]
D'oh! 

Thank you so much for clarifying this, Jarek! 

I'll revert my branch and edit while accounting for your comments, and then make a new pull. Are we allowed to edit the `readme.md`? If so, I'd like to add your clarification to the Password Rules section.

**Comment by Cldfire** [comment]
> D'oh!
> 
> Thank you so much for clarifying this, Jarek!
> 
> I'll revert my branch and edit while accounting for your comments, and then make a new pull. Are we allowed to edit the `readme.md`? If so, I'd like to add your clarification to the Password Rules section.

No worries!

Making this aspect of the password rules language more discoverable would be great; right now it's just a small note at the bottom of https://developer.apple.com/documentation/security/password_autofill/customizing_password_autofill_rules. Go ahead and mention that in the README in your PR and everyone can discuss if it makes sense to mention that here in this repo :)

**Comment by CasualDeveloper** [comment]
> Making this aspect of the password rules language more discoverable would be great; right now it's just a small note at the bottom of https://developer.apple.com/documentation/security/password_autofill/customizing_password_autofill_rules. Go ahead and mention that in the README in your PR and everyone can discuss if it makes sense to mention that here in this repo :)

Done! 😁

**Pull request closed without merging**
