### PR TITLE
Add password rule and change password URL for astonmartinf1.com

### PR DESCRIPTION
**Pull request by aaronraimist**
### Overall Checklist
- [x] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [x] The top-level JSON objects are sorted alphabetically
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

#### for change-password-URLs.json
- [x] There is no Well-Known URL for Changing Passwords (`https://example.com/.well-known/change-password`)
- [x] The URL either makes the experience better or no worse than being directed to just the domain in a non-logged-in state

#### for password-rules.json
- [x] The given rule isn't particularly standard and obvious for password managers
- [x] Generated passwords have been tested from this rule using the [Password Rules Validation Tool](https://developer.apple.com/password-rules/)
- [x] Information has been included about the website's requirements (eg. screenshots, error messages, steps during experimentation, etc.)
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)

screenshot

### CODE REVIEW

**Review by rmondello — CHANGES_REQUESTED** [review]
Do they allow any special characters? I know the rule doesn’t mention them, but we could test manually.

**Comment by aaronraimist** [comment]
Okay I tested some special characters. Everything I tried was allowed and I've added those to the rule.

**Comment by rmondello** [comment]
Two characters I can spot missing are `-` and ` ` (space). At this point, might be better to put `allowed: special;`.

**Comment by aaronraimist** [comment]
Yep those (and `{}`) worked as well so I switched over to `allowed: special;`

**Review by rmondello — APPROVED** [review]

**Pull request merged**
