### PR TITLE
walmart.com: remove min/max length attributes, add allowed characters to exclude not-allowed space

### PR DESCRIPTION
**Pull request by sashkab**
### Overall Checklist
- [x] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [x] The top-level JSON objects are sorted alphabetically
- [x] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

#### for websites-with-shared-credential-backends.json
- [ ] There's evidence the domains are related (SSL certificates, DNS entries, valid links between sites, legal documents etc.)
- [ ] The new group serves login pages on each of the included domains, and those login page accept accounts from the others. (For example, we don't associate `google.co.il` to `google.com`, because `google.co.il` redirects to `accounts.google.com` for authentication.)

#### for change-password-URLs.json
- [ ] There is no Well-Known URL for Changing Passwords (`https://example.com/.well-known/change-password`)
- [ ] The URL either makes the experience better or no worse than being directed to just the domain in a non-logged-in state

#### for password-rules.json
- [x] The given rule isn't particularly standard and obvious for password managers
- [ ] Generated passwords have been tested from this rule using the [Password Rules Validation Tool](https://developer.apple.com/password-rules/)
- [x] Information has been included about the website's requirements (eg. screenshots, error messages, steps during experimentation, etc.)
- [x] The PR isn't documenting something that would be a common practice among password managers (e.g. minimal length of 6)

Password change form at https://www.walmart.com/account/profile:

screenshot_2020 08 25_184727

Account registration page:

screenshot_2020 08 25_185211

### CODE REVIEW

**Comment by rmondello** [comment]
The fact that they’re declaring a minlength and maxlength on the <input> means that we might not need this rule at all in the repo. What does everyone think? @bradcush

**Comment by Scetch** [comment]
> The fact that they’re declaring a minlength and maxlength on the means that we might not need this rule at all in the repo. What does everyone think? @bradcush

I agree with this one, I'm not sure this needs to be included in the repo either. Over at @1Password we look at `minlength` and `maxlength` on fields in addition to the `passwordRules` to determine if we need to modify our default password rules.

**Comment by sashkab** [comment]
Looks like they don't accept space as valid character.

screenshot_2020 08 25_212813

Does it mean, we need to use something like this?

```
allowed: lower; allowed: upper; allowed: digit; allowed: [(-~!@#$%^&*_+=`|(){}[:;"'<>,.?]];
```

**Review by crypt096 — APPROVED** [review]

**Comment by rudyrichter** [comment]
I think @sashkab is right, we don't need min/max, but the "pattern" described in the html doesn't line up with [https://developer.apple.com/password-rules/](`passwordRules`)

**Comment by rmondello** [comment]
Thanks everyone for the help! I think this website is worthy of a passwordRule:

```
allowed: lower; allowed: upper; allowed: digit; allowed: [-(~!@#$%^&*_+=`|(){}[:;"'<>,.?]];
```

(Note that compared to @sashkab’s posted rule above, I move the `-` to be the first character of the character class.)

Why this rule:
- The website is giving us enough information about length.
- The pattern attribute is great for a validating user-typed text in a field, it’s cumbersome for password managers to work out how to meet. passwordRules were designed to be used by password managers.

**Comment by bradcush** [comment]
@rmondello I'm in agreement on adding this rule based on your reasoning without the min/max length attributes.

**Comment by sashkab** [comment]
removed min/max length, squashed into a single commit.

**Comment by rmondello** [comment]
Thanks @sashkab!

**Pull request merged**
