### PR TITLE
Remove obsolete websites with shared credential backend

### PR DESCRIPTION
**Pull request by MartinDevi**
There are quite a few domains which don't match the criteria. As started in the project [README](https://github.com/apple/password-manager-resources#websites-with-shared-credential-backends):

> It wouldn’t be appropriate to associate google.com.il to google.com because google.com.il redirects to accounts.google.com for sign-in, and google.com.il never serves a login page.

I'm guessing that these domains matched the criteria when they were added but the website maintainers have changed the behavior since then. 

By that logic, the domains in this MR are removed for the following reasons.
- alltrails.io redirects to alltrails.com
- ameritrade.com redirects to tdameritrade.com
- anylistapp.com redirects to anylist.com
- capitalone360.com redirects to capitalone.com
- citibankonline.com and citibank.com redirect to citi.com
- comcast.net redirects to xfinity.com
- discordapp.com redirects to discord.com
- getdropbox.com redirects to dropbox.com
- microsoft.com and skype.com use live.com SSO
- office.com uses microsoftonline.com SSO
- mojang.com redirects to minecraft.net
- sonyentertainmentnetwork.com doesn't seem to exist anymore
- square.com redirects to squareup.com

- [z] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)
- [z] The top-level JSON objects are sorted alphabetically
- [z] There are no [open pull requests](https://github.com/apple/password-manager-resources/pulls) for the same update

### CODE REVIEW

**Comment by rmondello** [comment]
I think this is helping to show that we need a richer schema here. Some of these are historical entries, which can still be useful for offering cleanup on the client. @Cldfire, I think this is more fuel for the conversations we’ve been having about this.

Really seems like we need a new, richer schema here, overall, which can express more types of relationships.

**Comment by Cldfire** [comment]
Absolutely; these would all be a great fit for the format proposed in #389.

I plan on getting around to updating the RFC with a format that more closely integrates with what exists today soon!

**Review by CyberFlameGO — APPROVED** [review]
I agree with this PR’s purpose

**Review by dmmaslenn — APPROVED** [review]

**Comment by dmmaslenn** [comment]
This PR was opened for a while resulting into merge conflicts, so I have tried to address conflicts by updating PR with latest main, but it does not merge cleanly and fails websites-shared-credentials test.
Please feel free to update this PR and make tests pass.

**Comment by dmmaslenn** [comment]
Closing this PR due to merge conflicts, please feel free to reopen this PR.

**Pull request closed without merging**
