### PR TITLE
add otto.de

### PR DESCRIPTION
**Pull request by vossni**

### CODE REVIEW

**Comment by rmondello** [comment]
This rules seem pretty reasonable to me, and not something that would trip any password manager up. I don’t think these are worth inclusion in the project, but will keep this open for discussion for a bit.

**Comment by ttuellmann** [comment]
> I don’t think these are worth inclusion in the project, but will keep this open for discussion for a bit.

Well, it is the second largest online retailer in Germany:

<a href="https://de.statista.com/prognosen/646009/top-online-shops-deutschland-ecommercedb" rel="nofollow">Statistik: Umsatzstärkste Online-Shops in Deutschland 2018 (in Millionen Euro) | Statista</a><br />Mehr Statistiken finden Sie bei  <a href="https://de.statista.com" rel="nofollow">Statista</a>

**Comment by DerJuulsn** [comment]
@ttuellmann It's not about the website itself. It's about the rules. It just says "not less than 8 chars" and that's not worth it to implement, because a password manager wouldn't probably generate a password less than 8 chars.

**Comment by ttuellmann** [comment]
@DerJuulsn thanks for the clarification. I figured, the technical requirements would be lower, since something like 

```
    "beglammed.com": {
        "password-rules": "minlength: 6;"
    },
```

is already included.

Never mind then.

**Comment by DerJuulsn** [comment]
@ttuellmann thanks, solved in #153

**Pull request closed without merging**
