### PR TITLE
Adding web-interface information to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by DerJuulsn**
I hope the formulation is kinda fine :)

### CODE REVIEW

**Comment by rmondello** [comment]
Hi @DerJuulsn ,

We recently made a change to the project to clarify the source of contributions to the project. That involved us changing the pull request template to have this item:

- [ ] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)

Can you confirm that you agree to this?

**Comment by DerJuulsn** [comment]
Hey! Sure.

[x] I agree to the project's [Developer Certificate of Origin](https://github.com/apple/password-manager-resources/blob/main/DEVELOPER_CERTIFICATE_OF_ORIGIN.md)

**Comment by rmondello** [comment]
@DerJuulsn I really like your web interface idea, but for the project to officially endorse it, I think it’d need to operate using the contributor’s account. The bot account makes it hard to know who is submitting changes, which is important to us.

You could make it an OAuth-type app that signs in with the Github API and does actions using their account, but that might be way more work than you want to do. I’d totally understand.

**Comment by rmondello** [comment]
Closing due to inactivity. Feel free to re-open any time!

**Pull request closed without merging**
